### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by igorpooh1978** [oxcafedead/barcode-reader-emulator#10]
Hi all

When I start emulater I catch up exception.
```
lang.UnsatisfiedLinkError: Can't obtain InputStream for com/sun/jna/win32-x86-64/jnidispatch.dll
	at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:962)
	at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:922)
	at com.sun.jna.Native.<clinit>(Native.java:190)
	at com.sun.jna.NativeLibrary.<clinit>(NativeLibrary.java:96)
	at oxcafedead.barcodereader.keybind.windows.User32.<clinit>(User32.java:23)
	at oxcafedead.barcodereader.keybind.windows.HotkeyBindManagerWindowsAdaptor.bindKey(HotkeyBindManagerWindowsAdaptor.java:35)
	at oxcafedead.barcodereader.ui.HotkeyListeningThread.run(HotkeyListeningThread.java:53)
```

**Comment by oxcafedead** [comment]
Hi @igorpooh1978,

what version of emulator do you use? Is it a zip archive - downloaded from releases and unpacked? What operating system and how do you run the application?
It seems that classpath is broken. Do you have `jnidispatch.dll` in your distribution? It should be packed into `lib/jna-4.5.0.jar` (inner path is `com/sun/jna/win32-x86-64` if you unpack this `jar` file).
The more info you provide the more probability I'll be able to come up with the root cause and the fix.

**Comment by igorpooh1978** [comment]
Hi @oxcafedead 
It's latest version from here https://github.com/oxcafedead/barcode-reader-emulator/releases/tag/0.4.0
OS Win 10 x64 19042
Yes. I have this file
![image](https://user-images.githubusercontent.com/47010778/118392697-8d065a80-b643-11eb-8fe5-8f526d18a197.png)

BTW. When I starting emulator directly from zip archive application working well.
PS. I extracted this file into root folder from jar file and application started well

**Comment by oxcafedead** [comment]
@igorpooh1978
Could you please describe in details, how did you run the application when it didn't work? Like, was it from the command line, what was the working directory, where did you extract the initial `zip` archive and so on.

**Comment by oxcafedead** [comment]
Not relevant for a new `2.0.0-alpha` go version.
https://github.com/oxcafedead/barcode-reader-emulator/releases
